### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by awollsd** [bigplayalman/autochess#3]
it'ld be cool if you could put it so when mouse over a unit it popups it's ability (for new players so they can see synergies + abilities each unit has) all in one place

**Comment by bigplayalman** [comment]
i like the idea, I also liked how they added icons for synergies in the game, I might do the same.

**Comment by awollsd** [comment]
yeah i was actually going to suggest the icons for race/class as well just on like bottom corner or something. anyway great program is pretty cool.

only other thing i could think of is maybe an icon/button on each to open their individual wiki page (so ppl could see stats and what the abilities of each hero do, though idk if the wiki is updated or not. but would be too much to add it all yourself haha)

anyway great work <3

**Comment by bigplayalman** [comment]
I added an info bar when you click on the synergy or the hero. Will add hero ability info soon
