### ISSUE TITLE
Help desploy to shared hosting!

### ISSUE THREAD

**Issue by sadazs** [bigplayalman/autochess#5]
Hi!
if I have a domain.com on shared hosting and I create a dir domain.com/builder
how to put this code to and run on shared hosting on dir domain.com/builder
Many Thank!

**Comment by bigplayalman** [comment]
if you want to deploy it on shared hosting, use this branch [/gh-pages](https://github.com/bigplayalman/autochess/tree/gh-pages). download all the files and folders.  or if you have npm installed, you can run npm run build, it will build the site into the dist folder, you can copy that then.
